apiVersion: v2
name: shomer-ssr
description: Shomer authorization SSR frontend (login + account UI, OIDC client).
type: application
version: 1.0.3
appVersion: "1.0.3"
icon: https://raw.githubusercontent.com/goabonga/shomer/main/assets/shomer.svg
