apiVersion: v2
name: shomer-job
description: Shomer background job (polling worker with signal-based shutdown).
type: application
version: 1.3.0
appVersion: "1.4.0"
icon: https://raw.githubusercontent.com/goabonga/shomer/main/assets/shomer.svg
home: https://github.com/goabonga/test-pipelilne-multicz
sources:
  - https://github.com/goabonga/test-pipelilne-multicz
maintainers:
  - name: Chris
    email: goabonga@pm.me
